# Site Configuration

# The base hostname and protcol.
# The subpath of the site.
# Exclude these files and folders.

# url: "http://www.silviabrown.co"
# baseurl: "/"
exclude: [".gitignore", "gulpfile.js", "package.json", "LICENSE.txt", "README.md", "node_modules"]

# Meta information.
title: Silvia Brown
description: "Silvia Brown's Work"

# Header text.
header_text: >
  <h1>Header text placeholder.</h1>
  <p>Paragraphy text placeholder.</p>

# Footer text.
footer_text: >
  <p>Footer test placeholder.</p>

# Contact information.
rss: false
email: hello@silviabrown.co

# Social network information.
behance:
dribbble: silscript
facebook:
flickr:
github: silscript
google_plus:
instagram: silscript
linkedin: silscript
pinterest: silscript
reddit:
rdio: silscript
soundcloud:
stack_exchange:
tumblr:
twitter: silscript
youtube:

# Strings information.
string_continue: "Read more ..."
string_email: "Email"
string_follow_on: "Follow me on"
string_follow_rss: "Follow RSS feed."
string_next: "Next"
string_prev: "Previous"

# Site pagination.
paginate: 100
paginate_path: "blog/page:num"

# Site collections.
collections:
  work:
    output: true
    permalink: /work/:path/

# Site build settings.
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
