# Site Configuration

# The base hostname and protcol.
# The subpath of the site.
# Exclude these files and folders.

# url: "http://www.silviabrown.co"
# baseurl: "/"
exclude: [".gitignore", "gulpfile.js", "package.json", "LICENSE.txt", "README.md", "node_modules"]

# Meta information.
title: Silvia Brown
description: "Silvia Brown's Work"
