# Site Configuration

# The base hostname and protcol.
# The subpath of the site.
# Exclude these files and folders.

# url: "http://www.silviabrown.co"
# baseurl: "/"
exclude: [".gitignore", "gulpfile.js", "package.json", "LICENSE.txt", "README.md", "node_modules"]

# Meta information.
title: Silvia Brown
description: "Silvia Brown's Work"

# Header text.
header_text: >
  <h1>Header text placeholder.</h1>
  <p>Paragraphy text placeholder.</p>

# Footer text.
footer_text: >
  <p>Footer test placeholder.</p>

# Contact information.
rss: false
email: hello@silviabrown.co

# Social network information.
behance:
dribbble: silscript
facebook:
flickr:
github: silscript
google_plus:
instagram: silscript
linkedin: silscript
pinterest: silscript
reddit:
rdio: silscript
soundcloud:
stack_exchange:
tumblr:
twitter: silscript
youtube:
